#!/usr/bin/env node

var commander = require('commander');

var fs = require('fs');

var options = {encoding: 'utf8'};

program()
	options

var start = Date.now();
fs.readFile('./file1', options, function(err, contents) {
	console.log(err);
	console.log(contents);
	console.log('took %s milliseconds to read', Date.now()- start);


});

