#!/usr/bin/env node

var program = require('commander');

var fs = require('fs');

var options = {encoding: 'utf8'};


program
  .version('0.0.1')
  .option('-n, --number', 'Report just the number of words')
  .option('-v, --verbose',  'Be more verbose, report timing information')
  .parse(process.argv);

var file1 = program.args[0];
var file2 = program.args[1];
var start = Date.now();

fs.readFile(file1, options, function(err, contents1) {
	
	fs.readFile(file2, options, function(err, contents2) {
		var arr1 = contents1.split(' ');
		var arr2 = contents2.split(' ');
		
		// console.log(err);
		console.log('Second file reads: ' + contents2);
		// console.log('took %s milliseconds to read', Date.now()- start);
		// console.log(err);
		console.log('First file reads: ' + contents1);
		console.log('took %s milliseconds to read', Date.now()- start);
		console.log('arr1: %j arr2: %j', arr1, arr2);
	});

});



// console.log('What file would youl like to read? :');
// if (program.peppers) console.log('  - peppers');
// if (program.pineapple) console.log('  - pineapple');
// if (program.bbq) console.log('  - bbq');
// console.log('  - %s cheese', program.cheese);

